site_name: Ca MEP ?
theme:
  name: mkdocs
  custom_dir: custom_theme

  # logo: assets/logo/scikit_eds.svg
  # favicon: assets/logo/scikit_eds.svg


nav:
  - index.md

plugins:
    - macros

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - codehilite
